spring:
  application:
    name: twoc-depot
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/depot?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 756433
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.two.depots.entity

server:
  port: 9001



